version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: madnikulin50/makves:latest
    restart: always
    environment:
      CONF: '{"orm": {"host": "db", "pwd": "example", "user": "postgres", "dbname": "postgres" } }'
    ports:
      - 8000:8000